[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Enable the Next.js Runtime
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle API routes specifically
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server-edge"
  status = 200
  force = true

# This single redirect handles all other routes properly for Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server-edge"
  status = 200
  force = true

# Enforce HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
