[build]
  # Directory to publish (relative to root of your repo)
  publish = "public"
  # Default build command
  command = "npm install"
  # Directory with Netlify Functions
  functions = "netlify/functions"

# Redirect all API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Enforce HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Handle single-page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net https://www.gstatic.com https://cdnjs.cloudflare.com 'unsafe-inline'; style-src 'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com 'unsafe-inline'; connect-src 'self' https://api.github.com https://*.supabase.co; img-src 'self' data:;"